module.exports = {
  
  USER_EVENT: 'USER_EVENT',
  ACTION: 'ACTION',
  STATE: 'STATE',

  TRIPS_A2B_CHANGED: 'TRIPS_A2B_CHANGED',
  TRIPS_A2C_CHANGED: 'TRIPS_A2C_CHANGED',
  TRIPS_B2A_CHANGED: 'TRIPS_B2A_CHANGED',
  TRIPS_B2C_CHANGED: 'TRIPS_B2C_CHANGED',
  TRIPS_C2A_CHANGED: 'TRIPS_C2A_CHANGED',
  TRIPS_C2B_CHANGED: 'TRIPS_C2B_CHANGED',
  TRIPS_CHANGED: 'TRIPS_CHANGED',

  user_event:{
    SEATS_CHANGED: 'SEATS_CHANGED',
  },

  action:{
    SEATS_CHANGED: 'SEATS_CHANGED',
    TRIPS_A_CHANGED: 'TRIPS_CHANGED',
    TRIPS_B_CHANGED: 'TRIPS_B_CHANGED'
  },

  state:{
    RECIPE_STATE_CHANGED: 'RECIPE_STATE_CHANGED'
  }
}